version: '2.4'
services:
  postgis:
    image: postgis/postgis:13-master
    env_file: ./.env
    shm_size: 2g
    volumes:
     - "${POSTGRES_DATA}:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_EXT_PORT}:5432"